### ISSUE TITLE
Discord.py 2.0 changes

### ISSUE THREAD

**Issue by ltzmax** [ltzmax/maxcogs#28]
While discord.py 2.0 is unknown when it will be released or if it will ever happen and while no official statement, i'll leave this here for what cog needs changes and not.

**Comment by Arman0334** [comment]
If you convert all the cogs to dpy2, I suggest having them on a separate branch, because many people are still on dpy 1.7.3

**Comment by maxbooiii** [comment]
> If you convert all the cogs to dpy2, I suggest having them on a separate branch, because many people are still on dpy 1.7.3

Well they are not going to be converted until dpy 2.0 is actually a thing to everyone.

**Comment by Arman0334** [comment]
ah i see, thanks :)

**Comment by ltzmax** [comment]
This is complete and waiting for [discord.py to bump their version to 2.0 from alpha.](https://github.com/Rapptz/discord.py) + Red has to push their stuff to 3.5, Closing this as complete so i dont forget about this one. 3.5 needs to be out before August 31 and its not long until.

**If some has question or wants something more added, feel free to create an issue and mark it with dpy 2.0.**
