### ISSUE TITLE
[Suggestion] Add option to disable user pings in the veryfun cog

### ISSUE THREAD

**Issue by Nogooduser** [ltzmax/maxcogs#34]
My server has really been enjoying using this cog but there's one slight annoyance. Since the easiest way to interact with another user is by mentioning them, most of the time commands from veryfun are used people get pinged twice, once from the user invoking the command and once from the bot response right after. 

There are some users we really don't want to disturb with pings, so this isn't super ideal. 

It would be incredibly helpful if there was a toggle in this cog that makes the bot respond with the same embed but no user ping.

**Comment by ltzmax** [comment]
Hello, Thanks for your suggestion.

I'll be looking into this later today and implement something to disable the pings.
Regarding two pings: you can actually use user's ID as well so they don't get pinged 2 times.

**Comment by ltzmax** [comment]
Hello @Nogooduser i've added this. in [22de0a2](https://github.com/ltzmax/maxcogs/commit/016d9db891a9b5e4db5740213d8d3c83bca9236e). mentions are enabled by default. you can toggle this off from `[p]funset toggle`. per user settings will come later time. right now any mods or admins can toggle this off and on. 

if users want to be pinged i'd have to implement that later time, right now you can just toggle this off right away. It will show the user's name in the embed as before but will not ping if its toggled off.
