### ISSUE TITLE
[veryfun] A way to not specify anybody in the command arguments

### ISSUE THREAD

**Issue by Nogooduser** [ltzmax/maxcogs#37]
I realize this is a roleplaying cog so interaction between 2 users is the intended use.

But I noticed some of the people in my server like popping in and just sending one of the actions in a general manner to everyone who's online, rather than one specific user. To achieve this, everyone's been mentioning themselves to avoid pinging anyone in specific. 

While this works fine, it does look a bit odd for the embed to say, for example, "John hugged John". I think it could be a nice touch to allow a user to not specify anyone so the action goes out to everyone, just to make a bit less weird looking.

In my head this would either let you run the command with no arguments or let you run it with a specific preset argument, either of which would always give the same output. 

So for implementation 1 you could simply run ``.hug``  and the embed would say "[user] hugged everyone/the server/etc."

For implementation 2 would be something like ``.hug everyone``, with the embed being the same as example 1.

I'm not sure which is easier to add, but either works equally well in my view.

I saw an implementation with a generic "server" argument in [loveplay](https://github.com/coffeebank/coffee-cogs/tree/master/loveplay), another cog with this same purpose.

I know it is a tiny visual change, but I think it's one users would appreciate.

**Comment by ltzmax** [comment]
I wont be turning this cog into something like this as its not what the cog really is meant for. its meant to choose a user not an entire server. 

What i am thinking here while they mention themselves is that i can add something like `john doe hugs themselves` when they use the command against themselves. this is something i can do. Let me know if you want this.

Users can also use the name of a member, example `[p]hugs MAX` / `[p]hugs "john doe"` or [userid](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) `[p]hugs 0000000000001` to use the action commands.

**Comment by Nogooduser** [comment]
Totally understandable.

That suggestion is still better than the current implementation so I'd personally be fine with it still if you're willing to implement it.

**Comment by ltzmax** [comment]
Alright, pushed an update so now it should say `themselves` if they use the actions against themselves. [0002d32](https://github.com/ltzmax/maxcogs/commit/242c3f405f98ffb96ea6fd94e178a85fdfa5c142)

I will look for better improvements to the dpy 2.0 branch to have that ready ™️. I also have alot things in mind such as more roleplay commands that is yet not added and will be on dpy 2.0. there's for now no ETA when that will happen but when that will happen it'd be on master branch. 

Feel free to suggest more if you have something in mind that you wish to see.
